name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        apt update
        apt install valgrind
    - name: configure
      run: ./configure --prefix=/opt
    - name: make test
      run: make test
